# Generated by Django 4.1 on 2022-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_alter_entrada_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('comentario', models.TextField(max_length=400)),
            ],
        ),
    ]
